version: '3'

services:
  webserver:
    # hostname: myweb
    image: nginx:latest
    ports:
      - 8084:80
    volumes:
      - ./code:/code
      - ./config:/etc/nginx/conf.d
    links:
      - php

  php:
    image: php:7-fpm
    volumes:
      - ./code:/code

  # mysql_db:
  #   image:
