version: '3'

services:
  nginx:
    image: nginx:1.17
    container_name: webserver
    env_file:
      - .env
    ports:
      # - ${SERVER_PORT}:80
      - 8082:80
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
      - ./nginx/logs/error.log:/var/log/nginx/error.log
      - ./nginx/logs/access.log:/var/log/nginx/access.log
      - ./uploaded:/var/www/secops:ro
    # links:
    depends_on:
      - php

  php:
    build: ./php-fpm/
    container_name: php
    #image: php:7.4-fpm
    working_dir: /var/www/secops
    volumes:
      - ./uploaded:/var/www/secops
#     depends_on:
#       - database
